### ISSUE TITLE
The scssphp version being used is unmaintained

### ISSUE THREAD

**Issue by stof** [axllent/silverstripe-scss#5]
> Disclaimer: I'm not using that package (or even Silverstripe). I'm one of the scssphp maintainers and I found that package when looking at which open-source packages were requiring old versions of our library.

This package currently locks the scssphp package at 1.6 while the latest release is 1.10.0.

Looking at the history, the usage of the semver operator (`^`) was removed in your 1.6.1 release due to a compilation failure in Bootstrap 5 in scssphp 1.5.0. And since then, it has not been changed back.
This approach does not guarantee that you get latest bug fixes, because the scssphp team does not maintain multiple minor versions in parallel, backporting bugfix. We maintain a single branch per major version (i.e. we maintain the `1.x` branch and the `master` branch where we prepare 2.0) and we release either a patch version or a minor version depending on the kind of changes we merged (based on the semver rules). If a particular release is broken for you, a better approach would be to add a conflict rule for that version (for instance `"conflict": { "scssphp/scssphp": "1.5.0" }` than blocking all future releases).

It would be great if you could use the latest version of scssphp (I suggest going back to using the semver operator in the constraint, but that's your choice if you prefer releasing new versions each time we do a new release)

Btw, the timeline of that particular issue even makes it useless to lock to 1.4:

1. 15 May 2021: you report https://github.com/scssphp/scssphp/issues/397 to us
2. 16 May 2021: you lock scssphp to 1.4 in d0c3a58638336c199a273f129b40d6887dd130e9
3. 17 May 2021: we fix the issue in scssphp
4. 17 May 2021: we release scssphp 1.5.1 with the fix
5. 18 May 2021: you release [1.6.1](https://github.com/axllent/silverstripe-scss/releases/tag/1.6.1) with the locked dependency (now already unnecessary)

**Comment by axllent** [comment]
Firstly, thank you so much @stof for your continued development and maintenance of scssphp - it's truly an awesome package and you guys (the new maintainers) have not only continued support for the previously-unmaintained original, but continue development too. I use this on several projects I maintain (using either bootstrap 4 or 5).

Secondly, thank you again for the issue report - this completely slipped under my radar. After the previous breakage (ie: my report) it broke a number of sites running bootstrap 5, so required an emergency fix at the time. I agree, it would have been better to add that version as a conflict, however at the time I did not know whether it would get fixed or return. I had also not noticed that bootstap 5 was added to your tests in the 1.5.1 release - which puts my mind at ease ;-) It was my intention (at the time) to follow each scssphp release (which I did do) and test them locally before updating silverstripe-scss requirements (which I then forgot to do!).

As you suggested, I've removed the constraint from my package and released a new version to pull in the latest 1.* scssphp release. Thanks again for your hard work, I really appreciate it!
