### ISSUE TITLE
Silverstripe 5 support

### ISSUE THREAD

**Issue by Zazama** [axllent/silverstripe-scss#6]
Hi,

thank you for releasing this module, we've been using it on multiple websites for years and it's running very good!
I was wondering if you have any plans on upgrading it for Silverstripe 5, or if you would accept a pull request from me?
There might not be any code changes required, but I'd have to check first.

**Comment by axllent** [comment]
Hi @Zazama. I definitely am intending to continue to support this module in Silverstripe 5, however I haven't yet gotten around to even trying to install / run SS5, so this may take some time. With this said, I would very much appreciate if you could look into this and report your findings back to me, and we can take it from there (re: a PR).

**Comment by Zazama** [comment]
Cool! I checked all the used classes against the changelog and found no changes against any used method in this module, I will test it with SS5 in practice next week and report back (there are some instances where the changelog is incomplete right now, so testing is more important 🙂).

**Comment by Zazama** [comment]
I've tested it in practice and everything seems to be working on my end, from installing into a fresh instance to developing with it and setting to live.

The only change needed for `composer require` to work was setting the `silverstripe-framework` requirement to `^5` (https://github.com/axllent/silverstripe-scss/compare/master...Zazama:silverstripe-scss:upgrade-silverstripe5).

It probably would also be possible to set it to `^4 || ^5` to support both.

**Comment by axllent** [comment]
@Zazama Thanks so much for testing this. I finally got around to testing it myself and can confirm it works as expected. I have updated the code accordingly and released 1.8.1 which supports both 4 & 5.
